kustomize:
  images:
  - ghcr.io/movinvinusandha/frontend:a809700c50237401a3a4fe837f156c3429e3de96
  - ghcr.io/movinvinusandha/cartservice:a809700c50237401a3a4fe837f156c3429e3de96
  - ghcr.io/movinvinusandha/productcatalogservice:latest
  - ghcr.io/movinvinusandha/currencyservice:latest
  - ghcr.io/movinvinusandha/paymentservice:latest
  - ghcr.io/movinvinusandha/shippingservice:latest
  - ghcr.io/movinvinusandha/emailservice:latest
  - ghcr.io/movinvinusandha/checkoutservice:latest
  - ghcr.io/movinvinusandha/recommendationservice:latest
  - ghcr.io/movinvinusandha/adservice:latest
