kustomize:
  images:
  - ghcr.io/movinvinusandha/frontend:cf338b3a1d0da33cbfafe8829f2d20f75fac9345
  - ghcr.io/movinvinusandha/cartservice:cf338b3a1d0da33cbfafe8829f2d20f75fac9345
  - ghcr.io/movinvinusandha/productcatalogservice:latest
  - ghcr.io/movinvinusandha/currencyservice:latest
  - ghcr.io/movinvinusandha/paymentservice:latest
  - ghcr.io/movinvinusandha/shippingservice:latest
  - ghcr.io/movinvinusandha/emailservice:latest
  - ghcr.io/movinvinusandha/checkoutservice:latest
  - ghcr.io/movinvinusandha/recommendationservice:latest
  - ghcr.io/movinvinusandha/adservice:latest
