kustomize:
  images:
  - ghcr.io/movinvinusandha/frontend:latest
  - ghcr.io/movinvinusandha/cartservice:latest
  - ghcr.io/movinvinusandha/productcatalogservice:latest
  - ghcr.io/movinvinusandha/currencyservice:latest
  - ghcr.io/movinvinusandha/paymentservice:latest
  - ghcr.io/movinvinusandha/shippingservice:latest
  - ghcr.io/movinvinusandha/emailservice:latest
  - ghcr.io/movinvinusandha/checkoutservice:latest
  - ghcr.io/movinvinusandha/recommendationservice:latest
  - ghcr.io/movinvinusandha/adservice:latest
